# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

    boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/9b9f118a-5159-4d57-b33a-b0c95e23479d";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7dcf3d7e-63f2-4ad8-8a56-f65388648271";
      fsType = "btrfs";
      options = [ "subvol=nixos" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/7dcf3d7e-63f2-4ad8-8a56-f65388648271";
      fsType = "btrfs";
      options = [ "subvol=nixos/var" ];
    };

  fileSystems."/var/lib" =
    { device = "/dev/disk/by-uuid/7dcf3d7e-63f2-4ad8-8a56-f65388648271";
      fsType = "btrfs";
      options = [ "subvol=nixos/var/lib" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/7dcf3d7e-63f2-4ad8-8a56-f65388648271";
      fsType = "btrfs";
      options = [ "subvol=nixos/var/log" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/7dcf3d7e-63f2-4ad8-8a56-f65388648271";
      fsType = "btrfs";
      options = [ "subvol=nixos/nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/7dcf3d7e-63f2-4ad8-8a56-f65388648271";
      fsType = "btrfs";
      options = [ "subvol=nixos/home" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
